application:
  name: ${name}
  formatted-version: ${version}

server:
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript,
      application/json
    min-response-size: 100
  error:
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    context-path: /


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ppm_app
    username: nnaik
    password:
    default-auto-commit: true
    auto-commit: true
    max-idle : 10
    max-wait : 10000
    min-idle : 5
    initial-size : 5
    validation-query : SELECT 1
    test-on-borrow : false
    test-while-idle : true
    minEvictableIdleTimeMillis : 300000
    hikari:
      maximum-pool-size: 100